[project]
name = "notebooklm-pipeline-backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "python-multipart",
  "pydantic>=2.7",
]

[tool.uvicorn]
factory = false
